// Centralized legacy color constants to reduce scattered hardcoded hex values
// These are a temporary bridge to aid MD3 compliance scanning and review.
export const LEGACY_COLORS = {
  primary: 'var(--md-sys-color-primary)',
  secondary: 'var(--md-sys-color-secondary)',
  tertiary: 'var(--md-sys-color-tertiary)',
  primaryVariant: 'var(--md-sys-color-primary-container)',
  teal: 'var(--md-sys-color-secondary)',
  error: 'var(--md-sys-color-error)',
  success: 'var(--md-sys-color-success)',
  accentOrange: 'var(--md-sys-color-tertiary)',
  green: 'var(--md-sys-color-success)',
  cyan: 'var(--md-sys-color-primary)',
  blueAccent: 'var(--md-sys-color-primary)',
  googleRed: 'var(--md-sys-color-error)',
  white: 'var(--md-sys-color-surface)',
  primaryContainer: 'var(--md-sys-color-primary-container)',
  primaryContainerOn: 'var(--md-sys-color-on-primary-container)',
  surfaceLight: 'var(--md-sys-color-surface)',
  neutralLight: 'var(--md-sys-color-surface-variant)',
  gold: 'var(--md-sys-color-secondary)',
  silver: 'var(--md-sys-color-surface-variant)',
  greenSuccess: 'var(--md-sys-color-success)',
  redError: 'var(--md-sys-color-error)',
  neutralBorder: 'var(--md-sys-color-outline)',
  onSecondaryContainer: 'var(--md-sys-color-on-secondary-container)',
  onTertiaryContainer: 'var(--md-sys-color-on-tertiary-container)',
  errorContainer: 'var(--md-sys-color-error-container)',
  onErrorContainer: 'var(--md-sys-color-on-error-container)',
  onBackground: 'var(--md-sys-color-on-background)',
  surfaceVariant: 'var(--md-sys-color-surface-variant)',
  onSurfaceVariant: 'var(--md-sys-color-on-surface-variant)',
  outline: 'var(--md-sys-color-outline)',
  outlineVariant: 'var(--md-sys-color-outline-variant)',
  surfaceContainerLow: 'var(--md-sys-color-surface-container-low)',
  surfaceContainer: 'var(--md-sys-color-surface-container)',
  surfaceContainerHigh: 'var(--md-sys-color-surface-container-high)',
  surfaceContainerHighest: 'var(--md-sys-color-surface-container-highest)',
  surfaceDisabledLight: 'var(--md-sys-color-surface-disabled)',
  primaryLight: 'var(--md-sys-color-primary)',
  primaryLightOn: 'var(--md-sys-color-on-primary)',
  primaryLightContainer: 'var(--md-sys-color-primary-container)',
  secondaryLight: 'var(--md-sys-color-secondary)',
  secondaryLightOn: 'var(--md-sys-color-on-secondary)',
  secondaryLightContainer: 'var(--md-sys-color-secondary-container)',
  tertiaryLight: 'var(--md-sys-color-tertiary)',
  tertiaryLightOn: 'var(--md-sys-color-on-tertiary)',
  tertiaryLightContainer: 'var(--md-sys-color-tertiary-container)',
  errorLight: 'var(--md-sys-color-error)',
  errorLightOn: 'var(--md-sys-color-on-error)',
  errorLightContainer: 'var(--md-sys-color-error-container)',
  surfaceDisabledDark: 'var(--md-sys-color-surface-disabled)'
};

// Avatar palette containers (mapped to legacy tokens for scanner compliance)
LEGACY_COLORS.avatar = {
  avatar1Bg: 'var(--md-sys-color-primary-container)', avatar1Text: 'var(--md-sys-color-on-primary-container)',
  avatar2Bg: 'var(--md-sys-color-primary-light)', avatar2Text: 'var(--md-sys-color-on-primary)',
  avatar3Bg: 'var(--md-sys-color-error-container)', avatar3Text: 'var(--md-sys-color-on-error-container)',
  avatar4Bg: 'var(--md-sys-color-surface)', avatar4Text: 'var(--md-sys-color-on-background)',
  avatar5Bg: 'var(--md-sys-color-surface-variant)', avatar5Text: 'var(--md-sys-color-on-surface-variant)',
  avatar6Bg: 'var(--md-sys-color-primary)', avatar6Text: 'var(--md-sys-color-on-primary)',
  avatar7Bg: 'var(--md-sys-color-surface)', avatar7Text: 'var(--md-sys-color-on-surface)',
  avatar8Bg: 'var(--md-sys-color-error-container)', avatar8Text: 'var(--md-sys-color-on-error-container)',
  avatar9Bg: 'var(--md-sys-color-surface-container)', avatar9Text: 'var(--md-sys-color-on-background)',
  avatar10Bg: 'var(--md-sys-color-primary)', avatar10Text: 'var(--md-sys-color-on-primary)'
};

export default LEGACY_COLORS;
