// Palette colori M3 (light mode)
export const colorTokens = {
  primary: '#6750A4',
  onPrimary: '#FFFFFF',
  primaryContainer: '#EADDFF',
  onPrimaryContainer: '#21005D',
  secondary: '#625B71',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#E8DEF8',
  onSecondaryContainer: '#1D192B',
  tertiary: '#7D5260',
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#FFD8E4',
  onTertiaryContainer: '#31111D',
  error: '#BA1A1A',
  onError: '#FFFFFF',
  errorContainer: '#FFDAD6',
  onErrorContainer: '#410002',
  success: '#146C2E',
  onSuccess: '#FFFFFF',
  warning: '#7D5800',
  onWarning: '#FFFFFF',
  background: '#FFFBFE',
  onBackground: '#1C1B1F',
  surface: '#FFFBFE',
  onSurface: '#1C1B1F',
  surfaceVariant: '#E7E0EC',
  onSurfaceVariant: '#49454F',
  outline: '#79747E',
  outlineVariant: '#CAC4D0',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#313033',
  inverseOnSurface: '#F4EFF4',
  inversePrimary: '#D0BCFF',
  primaryFixed: '#EADDFF',
  onPrimaryFixed: '#21005D',
  primaryFixedDim: '#D0BCFF',
  onPrimaryFixedVariant: '#4F378B',
  secondaryFixed: '#E8DEF8',
  onSecondaryFixed: '#1D192B',
  secondaryFixedDim: '#CBC2DB',
  onSecondaryFixedVariant: '#4A4458',
  tertiaryFixed: '#FFD8E4',
  onTertiaryFixed: '#31111D',
  tertiaryFixedDim: '#EFB8C8',
  onTertiaryFixedVariant: '#633B48',
  surfaceDim: '#DED8E1',
  surfaceBright: '#FFFBFE',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#F7F2FA',
  surfaceContainer: '#F3EDF7',
  surfaceContainerHigh: '#ECE6F0',
  surfaceContainerHighest: '#E6E0E9',
};

// Palette colori M3 (dark mode)
export const darkColorTokens = {
  primary: '#D0BCFF',
  onPrimary: '#381E72',
  primaryContainer: '#4F378B',
  onPrimaryContainer: '#EADDFF',
  secondary: '#CBC2DB',
  onSecondary: '#332D41',
  secondaryContainer: '#4A4458',
  onSecondaryContainer: '#E8DEF8',
  tertiary: '#EFB8C8',
  onTertiary: '#492532',
  tertiaryContainer: '#633B48',
  onTertiaryContainer: '#FFD8E4',
  error: '#FFB4AB',
  onError: '#690005',
  errorContainer: '#93000A',
  onErrorContainer: '#FFDAD6',
  success: '#8DD99F',
  onSuccess: '#003912',
  warning: '#FFBE48',
  onWarning: '#402D00',
  background: '#141218',
  onBackground: '#E6E0E9',
  surface: '#141218',
  onSurface: '#E6E0E9',
  surfaceVariant: '#49454F',
  onSurfaceVariant: '#CAC4D0',
  outline: '#938F99',
  outlineVariant: '#49454F',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#E6E0E9',
  inverseOnSurface: '#313033',
  inversePrimary: '#6750A4',
  primaryFixed: '#EADDFF',
  onPrimaryFixed: '#21005D',
  primaryFixedDim: '#D0BCFF',
  onPrimaryFixedVariant: '#4F378B',
  secondaryFixed: '#E8DEF8',
  onSecondaryFixed: '#1D192B',
  secondaryFixedDim: '#CBC2DB',
  onSecondaryFixedVariant: '#4A4458',
  tertiaryFixed: '#FFD8E4',
  onTertiaryFixed: '#31111D',
  tertiaryFixedDim: '#EFB8C8',
  onTertiaryFixedVariant: '#633B48',
  surfaceDim: '#141218',
  surfaceBright: '#3B383E',
  surfaceContainerLowest: '#0F0D13',
  surfaceContainerLow: '#1D1B20',
  surfaceContainer: '#211F26',
  surfaceContainerHigh: '#2D2A32',
  surfaceContainerHighest: '#38343C',
};

// Tipografia M3
export const typographyTokens = {
  body1: { fontSize: '16px', lineHeight: '24px', fontWeight: '400' },
  body2: { fontSize: '14px', lineHeight: '20px', fontWeight: '400' },
  heading1: { fontSize: '32px', lineHeight: '40px', fontWeight: '400' },
  heading2: { fontSize: '24px', lineHeight: '32px', fontWeight: '400' },
  caption: { fontSize: '12px', lineHeight: '16px', fontWeight: '400' },
};

// Spaziature M3
export const spacingTokens = {
  '1': '4px',
  '2': '8px',
  '3': '12px',
  '4': '16px',
  '5': '20px',
  '6': '24px',
};

// Motion M3
export const motionTokens = {
  duration: {
    short1: '50ms',
    short2: '100ms',
    short3: '150ms',
    short4: '200ms',
    medium1: '250ms',
    medium2: '300ms',
    medium3: '350ms',
    medium4: '400ms',
    long1: '450ms',
    long2: '500ms',
    long3: '550ms',
    long4: '600ms',
    extraLong1: '700ms',
    extraLong2: '800ms',
    extraLong3: '900ms',
    extraLong4: '1000ms',
  },
  easing: {
    standard: 'cubic-bezier(0.2, 0.0, 0, 1.0)',
    standardDecelerate: 'cubic-bezier(0.0, 0.0, 0.0, 1.0)',
    standardAccelerate: 'cubic-bezier(0.3, 0.0, 1.0, 1.0)',
    emphasized: 'cubic-bezier(0.05, 0.7, 0.1, 1.0)',
    emphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1.0)',
    emphasizedAccelerate: 'cubic-bezier(0.3, 0.0, 0.2, 0.8)',
  },
};

// Breakpoints M3
export const breakpointTokens = {
  mobile: '600px',
  tablet: '905px',
  desktop: '1240px',
  large: '1440px',
};

export const tokens = {
  colors: {
    primary: 'var(--md-sys-color-primary)',
    onPrimary: 'var(--md-sys-color-on-primary)',
    secondary: 'var(--md-sys-color-secondary)',
    onSecondary: 'var(--md-sys-color-on-secondary)',
    background: 'var(--md-sys-color-background)',
    surface: 'var(--md-sys-color-surface)',
    error: 'var(--md-sys-color-error)',
    success: 'var(--md-sys-color-tertiary)', // Mapped to tertiary for success
    warning: 'var(--md-sys-color-outline)', // Mapped to outline for warning
  },
  typography: {
    body1: {
      fontSize: 'var(--md-sys-typescale-body-large-font-size)',
      lineHeight: 'var(--md-sys-typescale-body-large-line-height)',
      fontWeight: 'var(--md-sys-typescale-body-large-font-weight)',
    },
    body2: {
      fontSize: 'var(--md-sys-typescale-body-medium-font-size)',
      lineHeight: 'var(--md-sys-typescale-body-medium-line-height)',
      fontWeight: 'var(--md-sys-typescale-body-medium-font-weight)',
    },
    heading1: {
      fontSize: 'var(--md-sys-typescale-headline-large-font-size)',
      lineHeight: 'var(--md-sys-typescale-headline-large-line-height)',
      fontWeight: 'var(--md-sys-typescale-headline-large-font-weight)',
    },
    heading2: {
      fontSize: 'var(--md-sys-typescale-headline-medium-font-size)',
      lineHeight: 'var(--md-sys-typescale-headline-medium-line-height)',
      fontWeight: 'var(--md-sys-typescale-headline-medium-font-weight)',
    },
    caption: {
      fontSize: 'var(--md-sys-typescale-body-small-font-size)',
      lineHeight: 'var(--md-sys-typescale-body-small-line-height)',
      fontWeight: 'var(--md-sys-typescale-body-small-font-weight)',
    },
  },
  spacing: {
    1: 'var(--md-sys-spacing-1)',
    2: 'var(--md-sys-spacing-2)',
    3: 'var(--md-sys-spacing-3)',
    4: 'var(--md-sys-spacing-4)',
    5: 'var(--md-sys-spacing-5)',
    6: 'var(--md-sys-spacing-6)',
  },
  motion: {
    duration: 'var(--md-sys-motion-duration-short)',
    easing: 'var(--md-sys-motion-easing-standard)',
  },
  breakpoints: {
    mobile: '480px',
    tablet: '768px',
    desktop: '1024px',
    large: '1200px',
  },
};